# Generated by Django 4.1.13 on 2024-08-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(),
        ),
    ]
