# Generated by Django 4.1.13 on 2024-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_user_session_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.TextField(),
        ),
    ]
