# Generated by Django 4.1.13 on 2024-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remaining_days',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deadline',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
